import "../styles/globals.css";
import type { AppProps } from "next/app";
import { AppStyleWrapper, FlexOneUI } from "../components/style";
import FooterLinks from "../components/Footer";
import AppHeader from "../components/Header";
import Head from "next/head";
import { useRouter } from "next/router";
import FooterHome from "../components/FooterHome";
import NearLogContext from "../AppContext";

function MyApp({ Component, pageProps }: AppProps) {
  const { pathname } = useRouter();
  return (
    <>
      <Head>
        <title>Nearlog from Nearlend DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </Head>
      <NearLogContext>
        <AppStyleWrapper>
          <AppHeader />
          <FlexOneUI>
            <Component {...pageProps} />
          </FlexOneUI>
          {pathname !== "/" ? <FooterLinks /> : <FooterHome />}
        </AppStyleWrapper>
      </NearLogContext>
    </>
  );
}

export default MyApp;
