import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import HomePage from "./home-page";
import Portfolio from "./portfolio";

const Home: NextPage = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Nearlog from Nearlend DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
      </Head>
      {/* <HomePage /> */}
      <Portfolio />
    </React.Fragment>
  );
};

export default Home;
